
-- Film Industry Database DDL

-- 1) Role
-- Lookup of creditable roles (e.g., Director, Writer, Lead Actor).
-- RoleType indicates where a role applies: Crew, Cast, or Both.

CREATE TABLE Role (
    RoleID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    RoleName    VARCHAR2(100) NOT NULL UNIQUE,
    RoleType    VARCHAR2(50)  NOT NULL CHECK (RoleType IN ('Crew', 'Cast', 'Both'))
);


-- 2) Actor
-- People who act in movies. Kept separate from Production_Staff.

CREATE TABLE Actor (
    ActorID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FirstName     VARCHAR2(100) NOT NULL,
    LastName      VARCHAR2(100) NOT NULL,
    DateOfBirth   DATE
);



-- 3) Production_Staff
-- Non-acting personnel (e.g., directors, writers, producers).

CREATE TABLE Production_Staff (
    StaffID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FirstName     VARCHAR2(100) NOT NULL,
    LastName      VARCHAR2(100) NOT NULL,
    DateOfBirth   DATE
);


-- 4) Character
-- Canonical fictional identities

CREATE TABLE Character (
    CharacterID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CharacterName VARCHAR2(200) NOT NULL UNIQUE,
    Description   CLOB
);


-- 5) Country
-- Lookup of countries
CREATE TABLE Country (
    CountryID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CountryName  VARCHAR2(200) NOT NULL UNIQUE,
    CountryCode  CHAR(2) UNIQUE  -- e.g., 'US', 'FR', 'JP'
);


-- 6) Language
-- Lookup of languages
CREATE TABLE Language (
    LanguageID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    LanguageName VARCHAR2(100) NOT NULL UNIQUE,
    LanguageCode CHAR(2) UNIQUE  -- e.g., 'en', 'es', 'ko'
);


-- 7) Studio
-- Production/distribution studios

CREATE TABLE Studio (
    StudioID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    StudioName            VARCHAR2(200) NOT NULL UNIQUE,
    HeadquartersCountryID NUMBER,
    YearFounded           NUMBER(4,0),

    CONSTRAINT FK_Studio_Country
        FOREIGN KEY (HeadquartersCountryID)
        REFERENCES Country(CountryID) ON DELETE SET NULL,

    CONSTRAINT CHK_Studio_Year
        CHECK (YearFounded > 1880 AND YearFounded <= 2025)
);


-- 8) Genre
-- Movie genres (e.g., Action, Drama). Pure lookup.

CREATE TABLE Genre (
    GenreID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    GenreName VARCHAR2(100) NOT NULL UNIQUE
);


-- 9) Award
-- Awards and their awarding bodies.

CREATE TABLE Award (
    AwardID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    AwardName    VARCHAR2(200) NOT NULL,
    AwardingBody VARCHAR2(200),
    CONSTRAINT UQ_AwardName_AwardingBody UNIQUE (AwardName, AwardingBody)
);


-- 10) Movie
-- Core  entity which consists of title, release date, synopsis, runtime, rating.

CREATE TABLE Movie (
    MovieID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Title          VARCHAR2(255) NOT NULL,
    ReleaseDate    DATE,
    Synopsis       CLOB,
    Duration       NUMBER(4,0),   -- minutes
    MaturityRating VARCHAR2(10),  -- e.g., G/PG/PG-13/R/NC-17

    CONSTRAINT CHK_Movie_Duration CHECK (Duration > 0)
);

-- 11) User
-- Application users who review movies.
CREATE TABLE "User" (
    UserID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(100) NOT NULL UNIQUE,
    Email    VARCHAR2(255) NOT NULL UNIQUE,
    JoinDate DATE DEFAULT SYSDATE NOT NULL
);


-- 12) Review
-- One review per (Movie, User). Rating constrained to 1–10.

CREATE TABLE Review (
    ReviewID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MovieID     NUMBER NOT NULL,
    UserID      NUMBER NOT NULL,
    RatingScore NUMBER(2,0) NOT NULL,  -- 1–10
    ReviewText  CLOB,
    Timestamp   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_Review_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID),

    CONSTRAINT FK_Review_User
        FOREIGN KEY (UserID) REFERENCES "User"(UserID),

    CONSTRAINT UQ_Review_Movie_User UNIQUE (MovieID, UserID),
    CONSTRAINT CHK_Review_Rating CHECK (RatingScore >= 1 AND RatingScore <= 10)
);


-- 13) Movie_Genre
-- M:N bridge between Movie and Genre.

CREATE TABLE Movie_Genre (
    MovieID NUMBER NOT NULL,
    GenreID NUMBER NOT NULL,

    CONSTRAINT PK_Movie_Genre PRIMARY KEY (MovieID, GenreID),

    CONSTRAINT FK_MovieGenre_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieGenre_Genre
        FOREIGN KEY (GenreID) REFERENCES Genre(GenreID) ON DELETE CASCADE
);


-- 14) Movie_Studio
-- M:N bridge between Movie and Studio.

CREATE TABLE Movie_Studio (
    MovieID  NUMBER NOT NULL,
    StudioID NUMBER NOT NULL,

    CONSTRAINT PK_Movie_Studio PRIMARY KEY (MovieID, StudioID),

    CONSTRAINT FK_MovieStudio_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieStudio_Studio
        FOREIGN KEY (StudioID) REFERENCES Studio(StudioID) ON DELETE CASCADE
);


-- 15) Movie_Cast
--  link: which Actor plays which Character in which Movie.

CREATE TABLE Movie_Cast (
    MovieID     NUMBER NOT NULL,
    ActorID     NUMBER NOT NULL,
    CharacterID NUMBER NOT NULL,

    CONSTRAINT PK_Movie_Cast PRIMARY KEY (MovieID, ActorID, CharacterID),

    CONSTRAINT FK_MovieCast_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieCast_Actor
        FOREIGN KEY (ActorID) REFERENCES Actor(ActorID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieCast_Character
        FOREIGN KEY (CharacterID) REFERENCES Character(CharacterID) ON DELETE CASCADE
);


-- 16) Movie_Crew
-- M:N link: which Staff member holds which Role on which Movie.

CREATE TABLE Movie_Crew (
    MovieID NUMBER NOT NULL,
    StaffID NUMBER NOT NULL,
    RoleID  NUMBER NOT NULL,

    CONSTRAINT PK_Movie_Crew PRIMARY KEY (MovieID, StaffID, RoleID),

    CONSTRAINT FK_MovieCrew_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieCrew_Staff
        FOREIGN KEY (StaffID) REFERENCES Production_Staff(StaffID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieCrew_Role
        FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE CASCADE
);


-- 17) Movie_Awards
-- Award events (nomination/win) for a Movie, optionally tied
-- to an Actor OR Staff as recipient.

CREATE TABLE Movie_Awards (
    MovieAwardID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MovieID           NUMBER NOT NULL,
    AwardID           NUMBER NOT NULL,
    Recipient_ActorID NUMBER,
    Recipient_StaffID NUMBER,
    YearWon           NUMBER(4,0) NOT NULL,
    DidWin            CHAR(1) DEFAULT 'N' NOT NULL CHECK (DidWin IN ('Y', 'N')),

    CONSTRAINT FK_MovieAwards_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieAwards_Award
        FOREIGN KEY (AwardID) REFERENCES Award(AwardID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieAwards_Actor
        FOREIGN KEY (Recipient_ActorID) REFERENCES Actor(ActorID) ON DELETE SET NULL,

    CONSTRAINT FK_MovieAwards_Staff
        FOREIGN KEY (Recipient_StaffID) REFERENCES Production_Staff(StaffID) ON DELETE SET NULL,

    -- Either actor OR staff OR nobody, but not both
    CONSTRAINT CHK_MA_ONE_RECIPIENT CHECK (
        (Recipient_ActorID IS NOT NULL AND Recipient_StaffID IS NULL) OR
        (Recipient_ActorID IS NULL AND Recipient_StaffID IS NOT NULL) OR
        (Recipient_ActorID IS NULL AND Recipient_StaffID IS NULL)
    )
);


-- 18) Movie_Country
-- M:N bridge between Movie and Country (for co-productions).

CREATE TABLE Movie_Country (
    MovieID   NUMBER NOT NULL,
    CountryID NUMBER NOT NULL,

    CONSTRAINT PK_Movie_Country PRIMARY KEY (MovieID, CountryID),

    CONSTRAINT FK_MovieCountry_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieCountry_Country
        FOREIGN KEY (CountryID) REFERENCES Country(CountryID) ON DELETE CASCADE
);


-- 19) Movie_Language
-- M:N bridge between Movie and Language (for multilingual films).

CREATE TABLE Movie_Language (
    MovieID    NUMBER NOT NULL,
    LanguageID NUMBER NOT NULL,

    CONSTRAINT PK_Movie_Language PRIMARY KEY (MovieID, LanguageID),

    CONSTRAINT FK_MovieLanguage_Movie
        FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,

    CONSTRAINT FK_MovieLanguage_Language
        FOREIGN KEY (LanguageID) REFERENCES Language(LanguageID) ON DELETE CASCADE
);


-- 20) Audit_Log
-- Generic audit sink for triggers.

CREATE TABLE Audit_Log (
    LogID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TableName      VARCHAR2(100) NOT NULL,
    Operation      VARCHAR2(10)  NOT NULL, -- INSERT / UPDATE / DELETE
    OldData        CLOB,
    NewData        CLOB,
    ChangeTimestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ChangedBy      VARCHAR2(100) DEFAULT USER NOT NULL
);


-- Indexing 


-- Review
CREATE INDEX IX_Review_MovieID ON Review (MovieID);
CREATE INDEX IX_Review_UserID  ON Review (UserID);

-- Movie_Genre / Movie_Studio
CREATE INDEX IX_MovieGenre_GenreID  ON Movie_Genre (GenreID);
CREATE INDEX IX_MovieStudio_StudioID ON Movie_Studio (StudioID);

-- Movie_Cast
CREATE INDEX IX_MovieCast_ActorID     ON Movie_Cast (ActorID);
CREATE INDEX IX_MovieCast_CharacterID ON Movie_Cast (CharacterID);

-- Movie_Crew
CREATE INDEX IX_MovieCrew_StaffID ON Movie_Crew (StaffID);
CREATE INDEX IX_MovieCrew_RoleID  ON Movie_Crew (RoleID);

-- Movie_Awards
CREATE INDEX IX_MovieAwards_AwardID          ON Movie_Awards (AwardID);
CREATE INDEX IX_MovieAwards_RecipientActorID ON Movie_Awards (Recipient_ActorID);
CREATE INDEX IX_MovieAwards_RecipientStaffID ON Movie_Awards (Recipient_StaffID);
CREATE INDEX IX_MovieAwards_YearWon          ON Movie_Awards (YearWon);

-- Studio / Country / Language bridges
CREATE INDEX IX_Studio_CountryID          ON Studio (HeadquartersCountryID);
CREATE INDEX IX_MovieCountry_CountryID    ON Movie_Country (CountryID);
CREATE INDEX IX_MovieLanguage_LanguageID  ON Movie_Language (LanguageID);

